version: '3'
services:
  postgresql:
    build: ./postgresql
    expose: 
      - 5432
  react:
    build: ./react
    ports:
      - '80:80'
    restart: on-failure
  nodejs:
    build: ./nodejs
    ports:
      - '4000:4000'
    restart: on-failure
  
